swagger: "2.0"
info:
  description: Swagger file for the TirolGESUND APIs
  version: "1.0.0"
  title: Swagger REST TirolGESUND
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /v1/status:
    get:
      operationId: "api.v1.status.getStatus"
      tags:
        - "Status"
        - "V1"
      summary: "Status of the application and the version of the API"
      description: "Get status of API"
      responses:
        200:
          description: "Successful get staus of API"
          schema:
            $ref: "#/definitions/Status"

  /v1/garminDailySummaries:
    post:
      operationId: "api.v1.garminDailySummaries.createGarminDailySummaries"
      tags:
        - "Garmin"
        - "V1"
      summary: "Create daily summeries"
      description: "Create daily summeries"
      parameters:
        - in: "body"
          name: "garminDailySummaries"
          description: "List of daily summaries from Garmin"
          required: true
          schema:
            $ref: "#/definitions/GarminDailySummaries"
      responses:
        200:
          description: "Successful received data"

  /v1/garminSleepSummaries:
    post:
      operationId: "api.v1.garminSleepSummaries.createGarminSleepSummaries"
      tags:
        - "Garmin"
        - "V1"
      summary: "Create sleep summeries"
      description: "Create sleep summeries"
      parameters:
        - in: "body"
          name: "garminSleepSummaries"
          description: "List of sleep summaries from Garmin"
          required: true
          schema:
            $ref: "#/definitions/GarminSleepSummaries"
      responses:
        200:
          description: "Successful received data"

  /v1/garminStressSummaries:
    post:
      operationId: "api.v1.garminStressSummaries.createGarminStressSummaries"
      tags:
        - "Garmin"
        - "V1"
      summary: "Create stress summeries"
      description: "Create stress summeries"
      parameters:
        - in: "body"
          name: "garminStressSummaries"
          description: "List of stress summaries from Garmin"
          required: true
          schema:
            $ref: "#/definitions/GarminStressSummaries"
      responses:
        200:
          description: "Successful received data"
  /v1/garminUserMetricsSummaries:
    post:
      operationId: "api.v1.garminUserMetricsSummaries.createGarminUserMetricsSummaries"
      tags:
        - "Garmin"
        - "V1"
      summary: "Create User Metrics summeries"
      description: "Create User Metrics summeries"
      parameters:
        - in: "body"
          name: "garminUserMetricsSummaries"
          description: "List of User Metrics summaries from Garmin"
          required: true
          schema:
            $ref: "#/definitions/GarminUserMetricsSummaries"
      responses:
        200:
          description: "Successful received data"

definitions:
  Status:
    type: "object"
    properties:
      Version:
        type: "string"
    example:
      Version: "1.0.0"
  GarminDailySummaries:
    type: "object"
    properties:
      dailies:
        type: "array"
        items:
          $ref: "#/definitions/GarminDailySummary"
  GarminSleepSummaries:
    type: "object"
    properties:
      sleeps:
        type: "array"
        items:
          $ref: "#/definitions/GarminSleepSummary"
  GarminStressSummaries:
    type: "object"
    properties:
      stressDetails:
        type: "array"
        items:
          $ref: "#/definitions/GarminStressSummary"
  GarminUserMetricsSummaries:
    type: "object"
    properties:
      userMetrics:
        type: "array"
        items:
          $ref: "#/definitions/GarminUserMetricsSummary"
  GarminDailySummary:
    type: "object"
    properties:
      summaryId:
        type: "string"
      userId:
        type: "string"
      userAccessToken:
        type: "string"
      calendarDate:
        type: "string"
      startTimeInSeconds:
        type: "integer"
        format: "int32"
      startTimeOffsetInSeconds:
        type: "integer"
        format: "int32"
      activityType:
        type: "string"
      durationInSeconds:
        type: "integer"
        format: "int32"
      steps:
        type: "integer"
        format: "int32"
      distanceInMeters:
        type: "number"
        format: "float"
      activeTimeInSeconds:
        type: "integer"
        format: "int32"
      activeKilocalories:
        type: "integer"
        format: "int32"
      bmrKilocalories:
        type: "integer"
        format: "int32"
      consumedCalories:
        type: "integer"
        format: "int32"
      moderateIntensityDurationInSeconds:
        type: "integer"
        format: "int32"
      vigorousIntensityDurationInSeconds:
        type: "integer"
        format: "int32"
      floorsClimbed:
        type: "integer"
        format: "int32"
      minHeartRateInBeatsPerMinute:
        type: "integer"
        format: "int32"
      averageHeartRateInBeatsPerMinute:
        type: "integer"
        format: "int32"
      maxHeartRateInBeatsPerMinute:
        type: "integer"
        format: "int32"
      restingHeartRateInBeatsPerMinute:
        type: "integer"
        format: "int32"
      timeOffsetHeartRateSamples:
        type: "object"
      averageStressLevel:
        type: "integer"
        format: "int32"
      maxStressLevel:
        type: "integer"
        format: "int32"
      stressDurationInSeconds:
        type: "integer"
        format: "int32"
      restStressDurationInSeconds:
        type: "integer"
        format: "int32"
      activityStressDurationInSeconds:
        type: "integer"
        format: "int32"
      lowStressDurationInSeconds:
        type: "integer"
        format: "int32"
      mediumStressDurationInSeconds:
        type: "integer"
        format: "int32"
      highStressDurationInSeconds:
        type: "integer"
        format: "int32"
      stressQualifier:
        type: "string"
      stepsGoal:
        type: "integer"
        format: "int32"
      netKilocaloriesGoal:
        type: "integer"
        format: "int32"
      intensityDurationGoalInSeconds:
        type: "integer"
        format: "int32"
      floorsClimbedGoal:
        type: "integer"
        format: "int32"
  GarminSleepSummary:
    type: "object"
    properties:
      summaryId:
        type: "string"
      userId:
        type: "string"
      userAccessToken:
        type: "string"
      calendarDate:
        type: "string"
      startTimeInSeconds:
        type: "integer"
        format: "int32"
      startTimeOffsetInSeconds:
        type: "integer"
        format: "int32"
      durationInSeconds:
        type: "integer"
        format: "int32"
      unmeasurableSleepInSeconds:
        type: "integer"
        format: "int32"
      deepSleepDurationInSeconds:
        type: "integer"
        format: "int32"
      lightSleepDurationInSeconds:
        type: "integer"
        format: "int32"
      remSleepInSeconds:
        type: "integer"
        format: "int32"
      awakeDurationInSeconds:
        type: "integer"
        format: "int32"
      sleepLevelsMap:
        type: "object"
      validation:
        type: "string"
      timeOffsetSleepRespiration:
        type: "object"
      timeOffsetSleepSpo2:
        type: "object"
  GarminStressSummary:
    type: "object"
    properties:
      summaryId:
        type: "string"
      userId:
        type: "string"
      userAccessToken:
        type: "string"
      calendarDate:
        type: "string"
      startTimeInSeconds:
        type: "integer"
        format: "int32"
      startTimeOffsetInSeconds:
        type: "integer"
        format: "int32"
      durationInSeconds:
        type: "integer"
        format: "int32"
      timeOffsetStressLevelValues:
        type: "object"
      timeOffsetBodyBatteryDetails:
        type: "object"
  GarminUserMetricsSummary:
    type: "object"
    properties:
      summaryId:
        type: "string"
      userId:
        type: "string"
      userAccessToken:
        type: "string"
      calendarDate:
        type: "string"
      Vo2Max:
        type: "number"
        format: "float"
      fitnessAge:
        type: "integer"
        format: "int32"